# Mongo docker image
version: '3.7'
services:
  mongo:
    image: 'mongo:4.4.0-rc8-bionic'
    restart: on-failure
    ports:
    - 27017:27017
    volumes:
    - ./.mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root@123
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root@123
